# Generated by Django 4.2.20 on 2025-04-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
    ]
