services:
  - type: web
    name: sanifu-backend
    env: docker
    repo: https://github.com/Masudi2022/Sanifu
    dockerContext: ./Virtual/Backend/MyJourney     # Corrected path (this folder contains the manage.py file)
    dockerfilePath: ./Virtual/Backend/Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure--$bb+=r3(^+^&tl6mp+*zc$hc4dkq6$+w)o1j5^#cb!_(outi$
      - key: DEBUG
        value: False
      - key: DJANGO_LOGLEVEL
        value: info
      - key: DJANGO_ALLOWED_HOSTS
        value: sanifu-backend.onrender.com
      - key: DJANGO_CORS_ALLOWED
        value: http://localhost:5173

      # PostgreSQL values from Render
      - key: DATABASE_ENGINE
        value: django.db.backends.postgresql
      - key: DATABASE_NAME
        value: sanifu_db
      - key: DATABASE_USERNAME
        value: masud_sanifu
      - key: DATABASE_PASSWORD
        value: 97LDj0rmgCH8pncUj6iPOKKjWa8M3iV3
      - key: DATABASE_HOST
        value: dpg-d03tt37gi27c738d6hp0-a
      - key: DATABASE_PORT
        value: 5432

      # Set the correct Django settings module
      - key: DJANGO_SETTINGS_MODULE
        value: MyJourney.settings
