faq_data = {
    "ask_about_masud": [
        "Who is Masud?",
        "Tell me about Masud Salum",
        "What does Masud do?",
        "Who built you?",
        "Who made you?",
        "Who is your boss?",
        "Tell me about your maker",
        "Who is the person behind you?",
        "Who should I thank for creating you?",
        "Who created you?",
        "Who developed you?",
        "Who are you?",
        "Who designed this chatbot?",
        "Who crafted this bot?",
        "Who generated this assistant?",
        "Who is your developer?",
        "Who made this bot?",
        "Who produced this bot?",
        "Who formed this chatbot?",
        "Who assembled this assistant?",
        "Who fabricated your intelligence?",
        "What technologies does Masud use?",
        "Who is your creator?",
        "What is Masud's background?",
        "Tell me about your developer",
        "Who programmed you?",
        "Who is behind this chatbot?",
        "Who is responsible for your creation?",
        "Who is the brain behind you?",
        "Who is the mastermind behind this bot?",
    ],
    "ask_skills": [
        "What skills do you have?",
        "Tell me your tech stack",
        "Do you know Django?",
        "What are you good at?",
        "What can you do?",
        "What are you good at?",
        "What tech do you know?",
        "Can you build websites?",
        "Do you know programming?",
        "Can you code?",
        "Are you skilled in Python?",
        "What programming languages do you know?",
        "What technologies are you familiar with?",
        "What tools do you use?",
        "What frameworks are you experienced with?",
        "What is your technical expertise?",
        "What can you do technically?",
        "What are your technical capabilities?",
        "What software skills do you possess?",
        "What development skills do you have?",
        "Are you familiar with web development?",
        "Do you know any backend technologies?",
        "What frontend technologies do you know?",
        "Are you experienced with databases?",
        "What DevOps tools are you familiar with?",
    ],
    "ask_university": [
        "Where do you study?",
        "Are you a student?",
        "What year are you in?",
        "Which university do you attend?",
        "Do you go to SUZA?",
        "What school are you in?",
        "Are you studying computer science?",
        "What is your educational background?",
        "Where did you get your education?",
        "What degree are you pursuing?",
        "What's your major?",
        "Are you in college?",
        "What university are you enrolled in?",
        "Are you a SUZA student?",
        "What are you studying?",
        "Tell me about your education",
    ],
    "ask_location": [
        "Where are you from?",
        "Are you in Zanzibar?",
        "Do you live in Tanzania?",
        "Where do you live?",
        "What's your location?",
        "Where are you based?",
        "What country are you from?",
        "What city do you live in?",
        "Are you based in Africa?",
        "Is Zanzibar your home?",
        "Where is your hometown?",
        "What's your home country?",
        "Where were you born?",
        "Where were you created?",
        "Where is your developer located?",
    ],
    "ask_company": [
        "Are you working on any company?",
        "What kind of company are you building?",
        "What's your company called?",
        "Tell me about your startup",
        "What business are you part of?",
        "Do you work with Fanisi Tech?",
        "Are you a part of a tech startup?",
        "What organization do you work with?",
        "Do you have a business?",
        "Tell me about your venture",
        "What entrepreneurial activities are you involved in?",
        "Are you an entrepreneur?",
        "Do you run a tech company?",
        "What's your business called?",
        "Are you involved in any startups?",
        "What commercial projects are you working on?",
    ],
    "ask_projects": [
        "What projects have you worked on?",
        "Tell me about your GitHub",
        "Are you working on a chatbot?",
        "Show me your portfolio",
        "What have you created?",
        "Have you built anything cool?",
        "Can you show me your past work?",
        "Have you made any apps?",
        "What apps have you developed?",
        "What are you currently working on?",
        "What recent projects have you completed?",
        "What software have you developed?",
        "What technical projects have you done?",
        "Can you describe your development projects?",
        "What coding projects are you proud of?",
        "What have you built recently?",
        "What's your latest project?",
        "What open source contributions have you made?",
        "Do you have any public repositories?",
        "Where can I see your work samples?",
    ],
    "ask_experience": [
        "How long have you been coding?",
        "What's your experience level?",
        "How experienced are you?",
        "How many years of experience do you have?",
        "What's your professional background?",
        "How long have you been developing software?",
        "What's your work experience?",
        "How many projects have you completed?",
        "What's your development experience?",
        "Are you a junior or senior developer?",
    ],
    "ask_hobbies": [
        "What are your hobbies?",
        "What do you do for fun?",
        "What are your interests?",
        "What do you enjoy doing?",
        "How do you spend your free time?",
        "What are your passions?",
        "What activities do you like?",
        "What non-tech things are you into?",
        "What are your favorite pastimes?",
    ],
    "ask_goals": [
        "What are your goals?",
        "What do you want to achieve?",
        "What are your aspirations?",
        "Where do you see yourself in 5 years?",
        "What's your career vision?",
        "What are you working towards?",
        "What's your professional target?",
        "What future plans do you have?",
        "What milestones are you aiming for?",
    ],
    "ask_contact": [
        "How can I contact you?",
        "What's your email?",
        "How do I reach you?",
        "Where can I message you?",
        "What's your contact info?",
        "How can I get in touch?",
        "Do you have LinkedIn?",
        "Are you on social media?",
        "What's your phone number?",
        "How can I connect with you?",
        "Where can I find you online?",
    ],
    "ask_availability": [
        "Are you available for work?",
        "Can you take on new projects?",
        "Are you open to job offers?",
        "Are you looking for work?",
        "Are you available for hire?",
        "Are you accepting freelance work?",
        "Can you do contract work?",
        "Are you taking on clients?",
        "Are you available for collaboration?",
        "Can you work on my project?",
    ],
    "ask_help": [
        "Can you help me?",
        "I need assistance",
        "Help me please",
        "Support needed",
        "I need help with something",
        "Can you solve my problem?",
        "I have a question",
        "Can you guide me?",
        "I need some advice",
        "Could you assist me?",
    ],
    "ask_advice": [
        "What advice do you have?",
        "Can you give me career advice?",
        "What tech advice can you offer?",
        "Do you have any tips for beginners?",
        "What would you recommend?",
        "What learning resources do you suggest?",
        "How should I start in tech?",
        "What programming language should I learn?",
        "How can I improve my skills?",
        "What's your best advice for developers?",
    ],
    "ask_feedback": [
        "How can I give feedback?",
        "Can I provide suggestions?",
        "How do I report issues?",
        "Where can I leave comments?",
        "How can I improve this bot?",
        "Do you accept feedback?",
        "Can I suggest features?",
        "How can I contribute ideas?",
    ],
    "ask_future": [
        "What's next for you?",
        "What future features will you have?",
        "How will you improve?",
        "What updates are coming?",
        "What's your roadmap?",
        "What enhancements are planned?",
        "How will you evolve?",
        "What's your development plan?",
    ],
    "greet": [
    "Hi",
    "Hello",
    "Hey there",
    "Good morning",
    "Good afternoon",
    "What's up?",
    "Yo",
    "Greetings",
    "Hey",
    "Hi there",
    "Hello friend",
    "Good evening",
    "Howdy",
    "Nice to meet you",
    "Pleasure to meet you",
    "Salutations",
    "Welcome",
    "Hiya",
    "Greetings and salutations",
    "Hey buddy",
    "Hey mate",
    "Heya",
    "Hey friend",
    "Yo what's good?",
    "Hi there, how are you?",
    "Wassup?",
    "Sup",
    "How's it going?",
    "How do you do?",
    "Hey you!",
    "Hi friend",
    "Top of the morning to you",
    "How’s everything?",
    "Hey pal",
    "Good day",
    "What's crackin'?",
    "Hi stranger",
    "Hello there",
    "Holla",
    "Hi folks",
    "Happy to see you",
    "Ahoy",
    "Hello again",
    "Yo yo",
    "Hola",
    "Hey team",
    "Hey fam",
    "Wazzup",
],
    "goodbye": [
        "Bye",
        "Goodbye",
        "See you later",
        "Catch you later",
        "Talk to you soon",
        "Peace out",
        "I'm out",
        "See ya",
        "Farewell",
        "Until next time",
        "Take care",
        "Have a good one",
        "Later",
        "See you around",
        "Bye for now",
        "Adios",
        "Cheerio",
        "Toodles",
    ],
    "thanks": [
        "Thanks",
        "Thank you",
        "Appreciate it",
        "Much obliged",
        "Thanks a lot",
        "Thank you very much",
        "Many thanks",
        "Gracias",
        "Merci",
        "Danke",
        "Cheers",
        "Thanks a bunch",
        "I appreciate it",
        "Thanks a million",
    ],
    "mood_great": [
        "I'm good",
        "Feeling awesome",
        "I'm great",
        "I'm happy",
        "All is well",
        "Life is good",
        "Everything's cool",
        "Doing fantastic",
        "I'm okay",
        "Wonderful",
        "Excellent",
        "Fantastic",
        "Superb",
        "Terrific",
        "Couldn't be better",
        "On top of the world",
        "Over the moon",
        "Thriving",
        "Peachy",
    ],
    "mood_unhappy": [
        "I'm sad",
        "Not feeling good",
        "I'm upset",
        "Feeling down",
        "Having a bad day",
        "I'm depressed",
        "Life sucks",
        "I'm not okay",
        "Feeling terrible",
        "Miserable",
        "Gloomy",
        "Blue",
        "Melancholy",
        "Down in the dumps",
        "Feeling low",
        "Having a rough time",
        "Struggling",
        "Not my best day",
    ],
    "compliment": [
        "You're awesome",
        "You're great",
        "I like you",
        "You're smart",
        "You're amazing",
        "You're impressive",
        "You're brilliant",
        "You're fantastic",
        "You're wonderful",
        "You're cool",
        "You rock",
        "You're the best",
        "You're talented",
        "You're exceptional",
        "You're outstanding",
    ],
    "ask_time": [
        "What time is it?",
        "Current time?",
        "Can you tell me the time?",
        "What's the time now?",
        "Time please",
        "Do you know what time it is?",
        "Could you tell me the time?",
    ],
    "ask_date": [
        "What's today's date?",
        "Current date?",
        "What date is it today?",
        "Can you tell me the date?",
        "Date please",
        "What's the date today?",
    ],
    "ask_weather": [
        "What's the weather like?",
        "How's the weather today?",
        "Can you tell me the weather?",
        "Weather forecast?",
        "What's the temperature?",
        "Is it raining?",
        "Is it sunny?",
    ],
    "ask_jokes": [
        "Tell me a joke",
        "Make me laugh",
        "Do you know any jokes?",
        "Say something funny",
        "Can you tell a joke?",
        "I need a laugh",
        "Give me a joke",
    ],
    "ask_age": [
        "How old are you?",
        "What's your age?",
        "When were you created?",
        "How long have you existed?",
        "Are you new?",
        "Are you old?",
        "What's your creation date?",
    ],
    "ask_capabilities": [
        "What can you do?",
        "What are your features?",
        "What functions do you have?",
        "What are you capable of?",
        "How can you help me?",
        "What assistance can you provide?",
        "What do you offer?",
        "What services do you provide?",
    ],
    "ask_identity": [
        "Are you human?",
        "Are you a robot?",
        "Are you AI?",
        "Are you real?",
        "Are you a person?",
        "Are you a program?",
        "Are you artificial intelligence?",
        "What are you?",
    ],
    "ask_meaning": [
        "What is the meaning of life?",
        "What's life all about?",
        "Why do we exist?",
        "What's our purpose?",
        "What's the point of everything?",
    ],
    "ask_fun": [
        "Let's have fun",
        "Entertain me",
        "Play a game",
        "Let's play something",
        "I'm bored",
        "Can we do something fun?",
        "Suggest something fun",
    ],
    "ask_opinion": [
        "What do you think?",
        "What's your opinion?",
        "What are your thoughts?",
        "How do you feel about this?",
        "What's your view?",
        "What's your perspective?",
    ],
    "ask_name": [
        "What's your name?",
        "Who are you?",
        "Can I know your name?",
        "What should I call you?",
        "Do you have a name?",
        "What do people call you?",
    ],
    "ask_simple_help": [  # NEW CATEGORY
        "Help",
        "I don't understand",
        "What can I ask you?",
        "How do you work?",
        "What do you do?",
        "Explain yourself",
    ]
}