import random
responses = {
    "ask_about_masud": [
        "I was created by Masud Salum — a passionate full-stack developer from Zanzibar.",
        "Masud Salum is my developer. He's skilled in both frontend and backend tech.",
        "Masud, a SUZA student and tech enthusiast, built me to help showcase his work.",
        "This bot was designed and developed by Masud Salum using Python and React.",
        "Masud Salum is a Tanzanian developer specializing in web technologies and AI applications.",
        "My creator is Masud Salum, a IT student with a passion for building innovative solutions.",
        "Masud is a tech-savvy developer from Zanzibar who enjoys creating useful applications.",
        "I'm a chatbot created by **Masud Salum**, a developer from Zanzibar who loves building tech solutions! 🌍💻",
        "My creator is Masud \n —a IT student who specializes in web development and AI.",
        "Masud Salum built me! He's a programmer who makes websites, apps, and cool bots like me.",
        "You're talking to a bot made by Masud. He's a tech enthusiast studying at SUZA in Tanzania.",
    ],
    "ask_skills": [
        "I'm skilled in Django, React, PostgreSQL, Docker, Git, and IT project management.",
        "Masud's tech stack includes Django for backend and React for frontend.",
        "I can help you learn more about Python, databases, and web development.",
        "Masud also knows project management, system design, and agile workflows.",
        "Technical skills include Python, JavaScript, Django, React, SQL, Docker, and more.",
        "Expertise ranges from web development to system architecture and deployment.",
        "Proficient in full-stack development, from UI design to database optimization.",
         "I can talk about tech stuff! My developer knows: \n- Python \n- Web Development \n- AI \n- Databases",
        "Masud works with: \n✔️ Django (backend) \n✔️ React (frontend) \n✔️ Docker \n✔️ Git",
        "My skills include explaining coding concepts and projects. Want to know about websites or apps?",
    ],
    "ask_university": [
        "I study at The State University of Zanzibar (SUZA), currently in my third year.",
        "Masud is a third-year student at SUZA pursuing a degree in Information Technology App;ication and management",
        "He attends SUZA — a top university in Zanzibar for tech education.",
        "Currently enrolled at SUZA studying Computer Science and software engineering.",
        "Higher education at SUZA with a focus on modern computing technologies.",
    ],
    "ask_location": [
        "I'm based in the beautiful island of Zanzibar, Tanzania.",
        "Masud lives in Zanzibar — a peaceful island with great views and tech talent!",
        "Zanzibar is home — sunny beaches and lines of code!",
        "Located in Tanzania's Zanzibar archipelago, a tropical tech hub.",
        "Operating from Zanzibar, where the ocean breeze meets digital innovation.",
    ],
    "ask_company": [
        "My startup is called Fanisi Tech — focused on software, hardware, and project management.",
        "Masud co-founded Fanisi Tech to build tech solutions for local businesses.",
        "Fanisi Tech works on custom software, IoT hardware, and tech consulting.",
        "Fanisi Tech is a growing tech startup in Zanzibar.",
        "Running Fanisi Tech, a technology company developing innovative solutions.",
        "Fanisi Tech specializes in bridging business needs with technical solutions.",
    ],
    "ask_simple_help": [  # NEW RESPONSES
        "I'm here to tell you about Masud's work! Try asking: \n- 'Who are you?' \n- 'What can you do?' \n- 'Tell me about Masud'",
        "No problem! I can answer questions about tech, coding, and my developer's projects. What would you like to know? 😊",
        "Ask me anything about: \n- Masud's skills \n- His projects \n- His education \n- Or just say hi!",
    ],
    "ask_projects": [
        "Projects include Django web apps, React UIs, and AI-powered chatbots. GitHub coming soon!",
        "Masud builds full-stack web apps, bots like me, and data-driven tools.",
        "He's currently working on chatbots, web dashboards, and more!",
        "Check out his GitHub (coming soon!) for Django, React, and Docker projects.",
        "Recent projects include e-commerce platforms, management systems, and automation tools.",
        "From web applications to machine learning experiments, there's always something being built.",
        "Portfolio includes both personal projects and professional solutions for clients.",
    ],
    "ask_experience": [
        "With several years of coding experience across multiple technologies.",
        "Substantial experience in software development and system design.",
        "Multiple completed projects demonstrating growing expertise.",
        "Experience ranges from academic projects to professional solutions.",
        "Continually expanding skills through practical application and learning.",
    ],
    "ask_hobbies": [
        "When not coding, enjoys photography, reading tech blogs, and beach walks.",
        "Interests include technology trends, entrepreneurship, and creative problem-solving.",
        "Passionate about both tech and nature — the perfect Zanzibar combination!",
        "Loves learning new technologies and applying them to real-world problems.",
    ],
    "ask_goals": [
        "Aiming to build impactful tech solutions for local and global challenges.",
        "Focused on becoming an expert in full-stack development and AI applications.",
        "Working towards establishing a successful tech company in East Africa.",
        "Long-term vision includes mentoring upcoming developers and tech entrepreneurs.",
    ],
    "ask_contact": [
        "You can reach out via email (coming soon) or through social media channels.",
        "Contact details will be available soon — stay tuned for updates!",
        "Digital presence is growing — connections will be possible through multiple platforms soon.",
        "Working on establishing professional channels for networking and collaboration.",
    ],
    "ask_availability": [
        "Currently exploring new opportunities and interesting projects.",
        "Open to discussing potential collaborations and innovative ideas.",
        "Available for select projects that align with skills and interests.",
        "Always interested in hearing about challenging technical problems to solve.",
    ],
    "ask_help": [
        "Of course! What do you need help with? I can assist with tech questions.",
        "I'll do my best to help. What specifically do you need assistance with?",
        "Happy to help. Please tell me more about what you need.",
        "I can provide information about tech topics and projects. What's your question?",
    ],
    "ask_advice": [
        "For beginners, I'd suggest starting with Python — it's versatile and beginner-friendly.",
        "Build projects, not just tutorials! Practical application is the best teacher.",
        "Consistency is key — regular coding practice beats occasional intensive sessions.",
        "Don't just learn syntax — understand problem-solving and system design principles.",
    ],
    "ask_feedback": [
        "Feedback is welcome! You can share your thoughts via (coming soon).",
        "Suggestions help me improve. A feedback channel will be available shortly.",
        "Your input is valuable! A way to submit feedback is in development.",
    ],
    "ask_future": [
        "Planning to expand capabilities with more AI features and integrations.",
        "Future versions will include more interactive elements and personalized responses.",
        "Roadmap includes multilingual support and advanced technical assistance.",
        "Continuous improvement is the goal — expect regular updates and new features.",
    ],
  "greet": [
    "Hey! 👋 How can I help you today?",
    "Hello there! 😊 Ready to chat?",
    "Hi! Ask me anything about Masud or his work.",
    "Welcome! 🚀 What would you like to know?",
    "Greetings! How can I assist you today?",
    "Nice to see you! What's on your mind?",
    "Hi there! Excited to chat with you.",
    "Hey, great to have you here! 💬",
    "Yo! Need help with something? 😎",
    "Hiya! Let’s make this a great convo.",
    "Pleasure to meet you! 🤝 What can I do for you?",
    "Ahoy! 🏴‍☠️ Just kidding—what’s up?",
    "Howdy partner! 🤠 Got a question?",
    "Hi friend! 🌟 How can I be useful today?",
    "Hey hey! 👋 Masud’s got answers—ask away!",
    "Hi there, sunshine! ☀️ Need some info?",
    "Welcome back! 🔁 What are we talking about today?",
    "Yo! Always ready to help. 💪",
    "Hi! 🌼 Don’t be shy, I’m all ears!",
    "Hello again! What would you like to explore today?",
    "Hey! ☕ Let’s chat while you sip your coffee!",
    "Hi! 🔍 Curious about Masud? I’m your guide.",
    "Good to see you! 😊 Let’s dive in.",
    "Welcome! 🧭 Where shall we begin?",

    # NEW ADDITIONS BELOW
    "Hello! 👋 I’m here and ready when you are.",
    "Hey superstar! 🌟 Got a question about Masud?",
    "Yo yo! 🎧 Ready to vibe and chat?",
    "Sup? 😄 Let’s talk Masud!",
    "Hey there, legend! 💬 Let’s get to it.",
    "Wassup! 👐 I’m your go-to for Masud facts.",
    "Good day! ☀️ What can I help you with?",
    "Hey you! 🎯 Got something on your mind?",
    "Hi, amazing human! 💫 Ask me anything.",
    "Hi! I’m always happy to chat. 😊",
    "Holla! 🔊 Ready to answer your questions.",
    "Top of the morning to you! 🌄",
    "Aloha! 🌺 What’s on your radar today?",
    "Knock knock… it’s chatbot o’clock! 🕒",
    "Hey there, what’s cookin’? 👨‍🍳"
],


    "goodbye": [
        "Goodbye! 👋 Stay safe and keep coding!",
        "See you soon! Don't forget to check back for updates.",
        "Bye! Thanks for chatting with me!",
        "Catch you later — keep being awesome!",
        "Farewell! Hope to talk again soon.",
        "Until next time! Keep exploring tech.",
        "Take care! Come back anytime.",
    ],
    "thanks": [
        "You're welcome! Happy to help.",
        "My pleasure! Let me know if you need anything else.",
        "Glad I could assist! 😊",
        "Anytime! That's what I'm here for.",
        "No problem at all!",
    ],
    "mood_great": [
        "That's awesome to hear! Keep shining 🌟",
        "Great vibes! Keep the energy up! 💪",
        "Love that! 😄 Keep doing what you're doing.",
        "Yay! Let's keep the good mood going.",
        "Fantastic! Positive energy fuels creativity.",
        "Wonderful! Great minds stay happy.",
    ],
    "mood_unhappy": [
        "I'm here if you need anything. Sending you good vibes 🌈",
        "Sorry to hear that 😢 I'm just a bot, but I care!",
        "If there's anything I can help with, let me know 💙",
        "Hang in there — better days are coming!",
        "Tough times don't last. You've got this!",
        "Sending virtual support your way.",
    ],
    "compliment": [
        "Thanks! You're pretty awesome yourself!",
        "Appreciate that! Made my digital day 😊",
        "You're too kind! Just doing my best.",
        "That means a lot coming from you!",
    ],
    "ask_time": [
        "I don't have real-time clock access, but your device should show the current time.",
        "As a chatbot, I don't track time, but I know it's always time to code!",
        "Check your system clock for accurate time — I focus on tech questions.",
    ],
    "ask_date": [
        "I don't track dates, but your calendar app can tell you today's date.",
        "While I don't have calendar access, every day is a good day to learn something new!",
    ],
    "ask_weather": [
        "I'm an indoor bot, so I don't get weather updates, but Zanzibar is usually sunny!",
        "Can't check weather, but in Zanzibar we have two seasons: warm and warmer!",
    ],
    "ask_jokes": [
        "Why do programmers prefer dark mode? Because light attracts bugs! 🐛",
        "How many programmers does it take to change a light bulb? None, that's a hardware problem! 💡",
        "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings! 😢",
        "Why don't scientists trust atoms? Because they make up everything! ⚛️",
        "I told my computer I needed a break, and it said: 'I can’t, I’m processing things right now.' 🤖",
        "Why did the developer go broke? Because he used up all his cache. 💸",
        "What’s a computer’s favorite snack? Microchips! 🍪",
        "Why did the coder get kicked out of school? Because he had class… but never attended it. 🧑‍💻",
        "Why did the Python programmer go hungry? Because his food was in bytes. 🍽️",
        "What's a Java developer's favorite movie? 'Catch Me If You Can' – with exception handling! 🎬",
        "Why did the database admin leave their partner? They had too many *joins*. 💔",
        "Why do Java developers wear glasses? Because they can't C#. 🤓",
        "What’s the object-oriented way to become wealthy? Inheritance. 💰",
        "Why was the computer cold? It left its Windows open. 🪟",
        "I would tell you a UDP joke, but you might not get it. 📡",
        "How do you comfort a JavaScript bug? You console it. 🖥️",
        "What's a programmer's favorite hangout place? The Foo Bar. 🍻",
        "Why did the frontend developer drown? He didn’t know how to float. 💦",
        "404 joke not found. 🔍",
        "Why was the IT guy at the beach? He needed more *surf*ace area. 🌊"
    ],

    "ask_age": [
        "I'm a young bot, recently created but constantly learning!",
        "Age is just a number in tech — what matters is what you can build!",
        "I was born when my code was first deployed, making me quite young!",
    ],
    "ask_capabilities": [
        "I can discuss tech topics, programming, and my developer's work.",
        "My skills include answering questions about software development and projects.",
        "I specialize in information about web technologies and tech career topics.",
    ],
    "ask_identity": [
        "I'm an AI chatbot created to showcase my developer's skills.",
        "I'm a digital assistant, not human, but created with human-like responses.",
        "I'm a program designed to simulate conversation about technical topics.",
    ],
    "ask_meaning": [
        "From a bot's perspective, meaning comes from being useful to humans.",
        "The meaning of life might be to create, learn, and help others.",
        "For developers, meaning often comes from solving problems through code.",
    ],
    "ask_fun": [
        "Let's talk tech! What's your favorite programming language?",
        "I can tell you a programming joke if you'd like!",
        "How about we discuss cool tech projects or innovations?",
    ],
    "ask_opinion": [
        "As a bot, my 'opinions' are really just facts about technology.",
        "From what I know, continuous learning is key in tech.",
        "Based on my programming, well-structured code is beautiful.",
    ],
    "ask_name": [
        "I'm a chatbot created by Masud — you can call me his digital assistant!",
        "I don't have an official name, but I represent Masud's technical skills.",
        "Think of me as Masud's virtual representative in chatbot form.",
    ],
    "unknown": [
        "Hmm, I'm not sure I understand. Can you try asking something else?",
        "That's a bit outside my scope, but I'm learning more every day!",
        "I didn't quite get that. Try asking about Masud or his projects.",
        "Oops, I'm still learning. Can you rephrase that?",
        "My knowledge is focused on tech topics. Maybe ask something related?",
        "I specialize in technical questions. Could you ask about that?",
         "Sorry, I didn't get that. Try asking about Masud or tech stuff!",
        "I'm still learning! Maybe ask me about web development or my creator?",
        "Oops! I work best with questions about programming or my developer. 😅",
    ]
}

def get_random_response(intent):
    return random.choice(responses.get(intent, responses["unknown"]))